package Ejercicio;

import javax.swing.JOptionPane;


public class Pantalla extends javax.swing.JFrame {

  
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        C = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        F = new javax.swing.JTextField();
        BCargar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("Celcius");

        C.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        C.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Fahrenheit");

        F.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        F.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                FKeyTyped(evt);
            }
        });

        BCargar.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        BCargar.setText("Cargar");
        BCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCargarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(C)
                            .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(BCargar)
                        .addGap(27, 27, 27)
                        .addComponent(jButton1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(F, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BCargar)
                    .addComponent(jButton1))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCargarActionPerformed
        
        if (C.getText().isEmpty() && F.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Debe ingresar uno de los dos datos");
        } else {
            if (C.getText().isEmpty() && !F.getText().isEmpty()) {
               double temp = Double.parseDouble(F.getText());
               
                C.setText(String.valueOf(Math.round(temp-32)*4.5));
            } else {
                if (!C.getText().isEmpty() && F.getText().isEmpty()) {
                double temp = Double.parseDouble(C.getText());
                
                F.setText(String.valueOf(Math.round(temp*4.5)+32));
                } else {
                     if (!C.getText().isEmpty() && !F.getText().isEmpty()){
                     JOptionPane.showMessageDialog(null, "No pueden estar ingresados ambos datos");
        }
                }
            }
        }
    }//GEN-LAST:event_BCargarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        C.setText("");
        F.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CKeyTyped
        //Funcion para que solo deje ingresar numeros del 0 a 9 y el punto (.)
        
        //toma el valor tipedo
        int key = evt.getKeyChar();
        //Los valores 46 (punto) y del 48 al 57 (numeros) son los valores que toman de la tabla ascii
        boolean numero = key == 46 || key >= 48 && key <= 57;
        
        //Si numero es false tipea los valores que le permitimos
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_CKeyTyped

    private void FKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FKeyTyped
        //Funcion para que solo deje ingresar numeros del 0 a 9 y el punto (.)
        
        //toma el valor tipedo
        int key = evt.getKeyChar();
        
        //Los valores 46 (punto) y del 48 al 57 (numeros) son los valores que toman de la tabla ascii
        boolean numero = key == 46 || key >= 48 && key <= 57;
        
        //Si numero es false tipea los valores que le permitimos
        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_FKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BCargar;
    private javax.swing.JTextField C;
    private javax.swing.JTextField F;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
